# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app

  redis:
    image: "redis/redis-stack-server:latest"
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - ./redis-volume:/data
